### ISSUE TITLE
shape '[1, 5, 20]' is invalid for input of size 25 when running run_trainer.py

### ISSUE THREAD

**Issue by Akutchi** [RL-VIG/LibFewShot#40]
Hi,

I'm trying to use your library with a custom dataset that I created with images retreived from google image. The train/val.csv file is composed of seven classes each with 5 examples and the test.csv is composed of one image of each classes (see below pictures).

I have also the following .yaml config file that I -more or less - copy-pasted from your documentation,

```yaml
includes:
  - headers/dataZSL.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/Proto.yaml
  - backbones/Conv64F.yaml


epoch: 50
test_epoch: 5

pretrain_path: ~
resume: False

way_num: 5
shot_num: 5
query_num: 15
test_way: ~
test_shot: ~
test_query: ~
episode_size: 1
# batch_size only works in pre-train
batch_size: 128
train_episode: 10000
test_episode: 1000

backbone:
  name: Conv64F
  kwargs:
    is_flatten: True
    is_feature: False
    leaky_relu: False
    negative_slope: 0.2
    last_pool: True
```

the dataZSL.yaml file referenced in the header is the following file,

```yaml
data_root: ./core/data/fewshot/zslDataset
image_size: 84
use_memory: False
augment: True
augment_times: 1
augment_times_query: 1
```

If that is useful, I will precise that I'm using google colab to run the code.
With all that said, when I try to lunch the run_trainer.py program the following error occurs, 

Traceback (most recent call last):
  File "run_trainer.py", line 12, in <module>
    trainer.train_loop()
  File "/content/drive/MyDrive/Colab Notebooks/LibFewShot/core/trainer.py", line 72, in train_loop
    train_acc = self._train(epoch_idx)
  File "/content/drive/MyDrive/Colab Notebooks/LibFewShot/core/trainer.py", line 119, in _train
    prefetcher = data_prefetcher(self.train_loader)
  File "/content/drive/MyDrive/Colab Notebooks/LibFewShot/core/utils/utils.py", line 288, in __init__
    self.preload()
  File "/content/drive/MyDrive/Colab Notebooks/LibFewShot/core/utils/utils.py", line 292, in preload
    self.next_data = next(self.loader)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/content/drive/MyDrive/Colab Notebooks/LibFewShot/core/data/collates/collate_functions.py", line 169, in __call__
    return self.method(batch)
  File "/content/drive/MyDrive/Colab Notebooks/LibFewShot/core/data/collates/collate_functions.py", line 149, in method
    self.episode_size, self.way_num, self.shot_num + self.query_num
RuntimeError: shape '[1, 5, 20]' is invalid for input of size 25

I must say that I am quite lost in how to resolve this problem. If I can provide more information, don't hesitate to ask, 
Thank you.

![train](https://user-images.githubusercontent.com/23198041/166465434-061db8f1-7a53-44c0-8c9a-744c1ef20865.png)
_the two first classes in train.csv_

![test](https://user-images.githubusercontent.com/23198041/166465815-a82d9836-6c12-428c-bd79-fc28dd800c9f.png)
_the test.csv file_

PS : I removed the first column in the lib code in dataset.py in order to only get the two columns of interest
