### ISSUE TITLE
The computer does not have cuda, and it will report an error when running.

### ISSUE THREAD

**Issue by Dao1023** [RL-VIG/LibFewShot#82]
error report

```sh
python run_trainer.py
Traceback (most recent call last):
  File "run_trainer.py", line 25, in <module>
    main(0, config)
  File "run_trainer.py", line 13, in main
    trainer = Trainer(rank, config)
  File "**\LibFewShot\core\trainer.py", line 54, in 
__init__
    self.device, self.list_ids = self._init_device(rank, config)
  File "**\LibFewShot\core\trainer.py", line 590, in _init_device
    torch.cuda.set_device(self.rank)
  File "C:\Users\Dao\anaconda3\envs\libfewshot\lib\site-packages\torch\cuda\__init__.py", line 326, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
```

Windows 10
Python 3.7.16

```sh
Package                 Version
----------------------- ------------
absl-py                 2.0.0
cachetools              5.3.1
certifi                 2023.7.22
charset-normalizer      3.3.0
cycler                  0.11.0
einops                  0.6.1
fonttools               4.38.0
future                  0.18.3
google-auth             2.23.3
google-auth-oauthlib    0.4.6
grpcio                  1.59.0
idna                    3.4
importlib-metadata      6.7.0
joblib                  1.3.2
kiwisolver              1.4.5
Markdown                3.4.4
markdown-it-py          2.2.0
MarkupSafe              2.1.3
matplotlib              3.5.3
mdurl                   0.1.2
numpy                   1.21.6
oauthlib                3.2.2
packaging               23.2
pandas                  1.3.5
Pillow                  9.5.0
pip                     23.2.1
protobuf                3.20.3
pyasn1                  0.5.0
pyasn1-modules          0.3.0
Pygments                2.16.1
pyparsing               3.1.1
python-dateutil         2.8.2
pytz                    2023.3.post1
PyYAML                  6.0.1
requests                2.31.0
requests-oauthlib       1.3.1
rich                    13.6.0
rsa                     4.9
scikit-learn            1.0.2
scipy                   1.7.3
setuptools              68.2.2
six                     1.16.0
tensorboard             2.11.2
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
threadpoolctl           3.1.0
torch                   1.13.1
torchaudio              0.13.1
torchvision             0.14.1
typing_extensions       4.7.1
urllib3                 2.0.6
Werkzeug                2.2.3
wheel                   0.38.4
zipp                    3.15.0
```

The pytorch version have no cuda.

the main function of `run_trainer.py` 

```python
if __name__ == "__main__":
    # config = Config("./config/proto.yaml").get_config_dict()
    config = Config("./config/test_install.yaml").get_config_dict()

    if config["n_gpu"] > 1:
        os.environ["CUDA_VISIBLE_DEVICES"] = config["device_ids"]
        torch.multiprocessing.spawn(main, nprocs=config["n_gpu"], args=(config,))
    else:
        main(0, config)
```

`test_install.py`

```yaml
includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/Proto.yaml
  - backbones/Conv64F.yaml


device_ids: 0
way_num: 5
shot_num: 1
query_num: 15
episode_size: 1
train_episode: 100
test_episode: 100

backbone:
  name: Conv64F
  kwargs:
    is_flatten: True
    is_feature: False
    leaky_relu: False
    negative_slope: 0.2
    last_pool: True
```

`device.yaml`

```yaml
device_ids: 0 # determine GPU ids in bus order
n_gpu: 0 # select the number of gpus to use
seed: 2147483647 # random seed for numpy, torch and cuda
deterministic: True # option for torch.backends.cudnn.benchmark  and torch.backends.cudnn.deterministic
port: ~
```
